services:
  - type: web
    name: rkrecipe
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=0, no-cache
    redirects:
      - source: /*
        destination: /index.html
        status: 200